name: Is SNAPSHOT Version

on:
  workflow_call:
    outputs:
      is_snapshot_version:
        description: Flag that indicates whether the given version is snapshot version
        value: ${{ jobs.is-snapshot-version.outputs.is_snapshot_version }}

jobs:
  get-project-version:
    name: Get Maven Project Version
    uses: ./.github/workflows/get-project-version.yml
  is-snapshot-version:
    name: Is SNAPSHOT Version
    needs: get-project-version
    runs-on: ubuntu-latest
    outputs:
      is_snapshot_version: ${{ steps.is-snapshot-version.outputs.is_snapshot_version }}
    steps:
      - id: is-snapshot-version
        name: Is SNAPSHOT Version
        run: echo "is_snapshot_version=$(if [[ ${{ needs.get-project-version.outputs.project_version }} == *-SNAPSHOT ]]; then echo true; else echo false; fi)" >> $GITHUB_OUTPUT
