name: Maven Deploy Snapshot

on:
  workflow_run:
    workflows: [ "Maven Verify" ]
    branches: [ "main" ]
    types:
      - 'completed'

jobs:
  get-project-version:
    name: Get Maven Project Version
    if: github.event.workflow_run.event == 'push' && github.event.workflow_run.conclusion == 'success'
    uses: ./.github/workflows/get-project-version.yml
  is-snapshot-version:
    name: Is SNAPSHOT Version
    needs: get-project-version
    uses: ./.github/workflows/is-snapshot-version.yml
    with:
      project_version: ${{ needs.get-project-version.outputs.project_version }}
  deploy:
    name: Deploy SNAPSHOT with Maven
    needs: is-snapshot-version
    if: needs.is-snapshot-version.outputs.is_snapshot_version == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
          server-id: ossrh
          server-username: OSSRH_USERNAME
          server-password: OSSRH_TOKEN
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - name: Deploy with Maven
        run: mvn --batch-mode deploy
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
